steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t southamerica-east1-docker.pkg.dev/microservices-fh-nestjs/image-repo/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DB_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL'] #in building we pass the secret

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/microservices-fh-nestjs/image-repo/orders-ms',
      ]

availableSecrets:
  secretManager:
  - versionName: projects/705968253191/secrets/FH-ORDER_DB_URL/versions/1
    env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY